### ISSUE TITLE
Can't delete session cookie from browser after logout

### ISSUE THREAD

**Issue by gabtec** [pouchdb-community/pouchdb-authentication#100]
Since the cookie from couchdb is marked as httpOnly, and since my couchdb cookies won't expire, how can I delete it from browser after I perform db.logout() ?

**Comment by gabtec** [comment]
Not an issue anymore.
The db.getSession() still responde true, but the db.getUser() responde with 404 object not found, and I go from there.

**Comment by fasiha** [comment]
I can confirm @gabtec’s finding that although `db.getSession()` continues to produce meaningful output about the previously-logged-in user even after `db.logout()`, `db.getUser()` 404s. However, I’m still able to get `db.allDocs()` after `db.logout()` which concerns me a lot. How am I supposed to really-actually-no-kidding log out a user to prevent someone else from re-opening their browser and seeing the database?

**Comment by nolanlawson** [comment]
Is `db.allDocs()` accessing local data or remote data? If it's local, then anyone with access to the computer can access those files. You would need to destroy or encrypt the database (e.g. using crypto-pouch) to ensure that the user's files are secure.

Destroying the database on logout is a common pattern.

**Comment by fasiha** [comment]
Sorry, I forgot to mention it’s a *remote* db, hence my worry.
