### ISSUE TITLE
can't bring it to work

### ISSUE THREAD

**Issue by beckerIGG** [pouchdb-community/pouchdb-authentication#106]
Hi,
if i request the DB with the query below:
```js
function doSignIn() {
    remoteCouch.login('xxxxx', 'yyyyyyy', function(err, response) {
        console.log(response);
        //console.log(err);
        if (err) {
            if (err.name === 'unauthorized') {
                // name or password incorrect
            } else {
                // cosmic rays, a meteor, etc.
            }
        } else {
            remoteCouch.getUser('xxxxx', function(err, response) {
                console.log(response);
                console.log(err);
                if (err) {
                    if (err.name === 'not_found') {
                        // typo, or you don't have the privileges to see this user
                    } else {
                        // some other error
                    }
                } else {
                    // response is the user object
                    console.log(response);
                }
            });
        }
    });
}
```
i got the following response.
![response](https://cloud.githubusercontent.com/assets/7497356/16587560/851ae2c8-42cb-11e6-8737-08540f217996.jpg)
Below you will find the couch settings.
![httpd](https://cloud.githubusercontent.com/assets/7497356/16587555/8034d336-42cb-11e6-8f09-d9ef1e006299.png)
![cors](https://cloud.githubusercontent.com/assets/7497356/16587557/8321cc3e-42cb-11e6-8577-005d52929efd.png)
What am i doing wrong? i am not getting the user nor a response that a user is now logged in. SignUp works, but only at the second time. 
![create_user](https://cloud.githubusercontent.com/assets/7497356/16587821/b09ff022-42cc-11e6-9e4a-73997b36cb75.png)

First time it is not working. But after all the user is within the _user db. Any ideas, so far?
BR Thomas

**Comment by nolanlawson** [comment]
Sorry, I'm not sure what's going on from these images. Maybe check the **Network** tab in the Chrome dev tools to see what the response from CouchDB was?

**Comment by beckerIGG** [comment]
Hi,
okay i get it somehow to work on a local machine (http://127.0.0.1:5984/whatever_db). Signup of user and login works, i also get a cookie. However getSession() => name is still null and if i use a remote db on a different location (i copied the local. ini from local db to the remote one) i cannot make it. Also i do not get a cookie.
Any ideas?

**Comment by ptitjes** [comment]
@beckerIGG Have you fixed your problem ?
Otherwise could you tell more about your environment (browser, ...) ?

**Comment by ptitjes** [comment]
Closing this issue as it seems to be stale. Please do reopen a ticket if you still experience this.
