### ISSUE TITLE
Firefox Update 48 (Ubuntu) no cookie-header after authentication (?)

### ISSUE THREAD

**Issue by mmoscher** [pouchdb-community/pouchdb-authentication#113]
Disclaimer: I'm not sure if this is the right place to mention this bug/failure of FF, but it cost me about 5 hours to figure out. And it seems to be similar to the current chrome bug, since Firefox does not handle the CORS authentication after successful login correctly.
(Maybe someone else is currently experiencing this failure)

Using 
├── pouchdb#5.4.5
├── pouchdb-authentication#0.5.3
in an Ionic App I'm not longer able to retrieve user information using a remote CouchDB as endpoint. After a successful login and receiving the `set-cookie` header as well,  `getSession()` always returns
`{"ok":true,"userCtx":{"name":null,"roles":[]},"info":{"authentication_db":"_users","authentication_handlers":["oauth","cookie","default"]}}`. 

Inspecting the request shows that FF does not send any additional cookie header.

```
GET /_session HTTP/1.1
Host: ........ 
User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:48.0) Gecko/20100101 Firefox/48.0
Accept: application/json
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate
DNT: 1
Referer: http://localhost:8100/
Origin: http://localhost:8100
Connection: keep-alive
```

(cookie missing)

Using the latest available chromium version (Version 51.0.2704.79 Ubuntu 16.04 (64-bit)) everything works as expected.
Furthermore chromium does attach the retrieved cookie value in the next requests correctly.

**Comment by nolanlawson** [comment]
Hey, if this is something that worked in Firefox 47.0.1 but fails in Firefox 48, and if it continues to work in non-Firefox browsers, then perhaps you should file the issue on Firefox themselves? They have a page for this: https://bugzilla.mozilla.org/

Also if you could provide a live test case to reproduce, that would be very helpful. Looking over your description, I'm not sure where to begin. Are you unable to log back in again? Or is the problem that you logged in in Firefox 47 and are no longer logged in in Firefox 48?

**Comment by nolanlawson** [comment]
Also this doesn't seem similar to the Chrome 52 bug (#111) because the issue there is an empty CORS preflight header whereas here it's an empty cookie header, yes?

**Comment by ptitjes** [comment]
Closing this issue as it seems to be stale. Please do reopen a ticket if you still experience this.
