### ISSUE TITLE
{skipSetup: true} not working for me :(

### ISSUE THREAD

**Issue by Java-Jonas** [pouchdb-community/pouchdb-authentication#126]
I have the following line i my script.
`var db = new PouchDB('https://MYNAME.cloudant.com/MYDB/', {skipSetup: true})`
As you can see i am using cloudant. In the documentary it says that `{skipSetup: true}` would stop the authentidication-modal from popping up. Sadly it doesn't work for me.
Since i am using the "`db.login`" command i can just close the modal and still use the website as intended. But the modal is still super annoying. How do i keep this from happening. Thanks!

**Comment by nolanlawson** [comment]
This is not a pouchdb-authentication issue but rather a pouchdb issue. If you could use the pouchdb.js file and set a breakpoint for where skipSetup appears in the code and then debug, that would be very helpful. I am swamped right now and it is unlikely I'll be able to get to this issue within the next year.

**Comment by Java-Jonas** [comment]
So here is the code:
https://github.com/Java-Jonas/pouchdb-skip_setup-true-not-working
maybe you can have quick look :) 
the error could still be on my side.

**Comment by Java-Jonas** [comment]
I don' know exactly what happened but somehow it works now. 
Anyway, if someone else encounters this problem feel free to contact me. Maybe i can help.

**Comment by quarthex** [comment]
Did you tried using `skip_setup`option instead?

**Comment by vardas-bill** [comment]
@Java-Jonas I am having this problem and have tried every solution I can find but to no avail. Do you have any idea why it suddenly started working for you?

I am tearing my hair out so any help you could give would be hugely appreciated!

**Comment by Java-Jonas** [comment]
@verdas-bill I'm afraid this is waaaaay to long ago and i barely remember anything about it. Really sorry

**Comment by vardas-bill** [comment]
No problem thanks anyway.

 

Bill
