### ISSUE TITLE
CouchDB 2.0 support

### ISSUE THREAD

**Issue by nolanlawson** [pouchdb-community/pouchdb-authentication#128]
I've heard from many folks that CouchDB 2.0 doesn't work with this module. At the very least we should add tests using CouchDB 2 in addition to 1.6 and see which tests are failing.

**Comment by chriseyhorn** [comment]
Hey @nolanlawson, are there still known issues with CouchDB 2 and this project?

**Comment by SinanGabel** [comment]
Hi,

I am using pouchdb-auth. with CouchDB 2.0 (version 20 Dec. 2016) without
problems - have not encountered any at least.

Br,
Sinan

**Comment by chriseyhorn** [comment]
Thanks @SinanGabel, I will give it a go.

**Comment by NaTheVice** [comment]
they are using port 5986 instead of 5984 for the default _user database

**Comment by ptitjes** [comment]
Seems to work correctly. Closing.
