### ISSUE TITLE
feature-request: manage users

### ISSUE THREAD

**Issue by bkolaci** [pouchdb-community/pouchdb-authentication#129]
Very cool module.  It would be advantageous to have functions that return a list of users as well as a function to delete a user or mark them as deleted.

I'm looking to create a user management page to list, add, delete users, as well as set their roles to allow an admin to manage them.

**Comment by nolanlawson** [comment]
This module merely acts as a simple API over CouchDB authentication. You can fetch the `_users` document via e.g. `new PouchDB('http://example.com/_users').allDocs()` or even just fetching with normal ajax.

**Comment by ptitjes** [comment]
@bkolaci You now have two new methods to help you in PouchDB Authentication:
- `deleteUser` that deletes a user;
- `getUsersDatabaseUrl` that returns the users database url, so that you can query it.

You can now easily implement your admin page, so I'm closing this issue. Cheers.
