### ISSUE TITLE
NodeJS compatibility

### ISSUE THREAD

**Issue by natcohen** [pouchdb-community/pouchdb-authentication#141]
I think it's a must have, for security reasons, to be able to authenticate and login from the server!

**Comment by nolanlawson** [comment]
This was never one of my goals with this project, but anybody who wants to add the functionality is welcome. :) As long as it doesn't seriously degrade the browser version (e.g. adding huge polyfills).

**Comment by natcohen** [comment]
@nolanlawson I'm probably naive but I always thought couchdb was handling most of the job...hence I thought authentication was just sending and receiving requests to and from couchdb! What can't be handled by node and would require polyfills?

**Comment by SinanGabel** [comment]
@natcohen: see e.g. https://www.npmjs.com/package/superlogin

I have not used it myself but I know there are a few alternatives including
superlogin.

Br

**Comment by ptitjes** [comment]
Fixed by https://github.com/pouchdb-community/pouchdb-authentication/commit/5b61b004281e7b74adf2f19973f9c7edef75a702.
