### ISSUE TITLE
How to use with Envoy for 'database per user' pattern

### ISSUE THREAD

**Issue by sodevy** [pouchdb-community/pouchdb-authentication#142]
Thank you for this. I'm trying to use https://github.com/martinic/ember-simple-auth-pouch with https://github.com/cloudant-labs/envoy for a 'database per user' pattern.

Envoy has it's own authentication approach - basic http auth against the /_auth endpoint sets a cookie which creates a valid session. 

I'm having trouble figuring out in which plugin this would be implemented or how I would go about it. Any assistance would be greatly appreciated.

**Comment by ptitjes** [comment]
I'm afraid this may not be the best place to ask. pouchdb-authentication is made to work above CouchDB directly. You should ask on the envoy github. Also, from looking at their readme page, it seems that https://github.com/glynnbird/pouchdb-envoy handles uris with basic authentication.

Tell us if you find some simple way to make us compatible, please.
