### ISSUE TITLE
Does the concept of permissions exist in Pouch/Couch

### ISSUE THREAD

**Issue by CrashyBang** [pouchdb-community/pouchdb-authentication#146]
I have scoured the internet, asked around, and looked at your uses cases listed in the ReadMe but I still haven't been able to find any material related to the concept of permissions or teirs.

I have an application which has users with different permissions i.e `perm_a` `perm_b` `perm_c` etc...

A users permisions will dictate the databases they have access to i.e a user with `perm_a` has access to `db_a` and a user with `perm_b` has access to `db_b` etc... A user can also have multiple permissions giving them access to multiple db's

I also only want to cache a db if the user has access to it, so that the only data stored in the browser is data the user already has access to.

Is this kind of setup even possible?

I think multiple databases is what I am after but I am not sure?

**Comment by ptitjes** [comment]
I believe what you want is called `roles` in the CouchDB terminology. You should read the following:
- http://docs.couchdb.org/en/2.1.1/intro/security.html?highlight=roles
- http://docs.couchdb.org/en/2.1.1/api/database/security.html?highlight=roles
- http://docs.couchdb.org/en/2.1.1/json-structure.html#security-object
- and maybe http://docs.couchdb.org/en/2.1.1/ddocs/ddocs.html?highlight=roles#filter-functions

What you want to achieve is totally possible with roles in CouchDB.

I will close this issue as this is more related to organising your databases in CouchDB than authentication through pouchdb-authentication.
