### ISSUE TITLE
Inconsistency between `skip_setup` and `skipSetup` in example code

### ISSUE THREAD

**Issue by flimzy** [pouchdb-community/pouchdb-authentication#147]
As [pointed out today on SO](http://stackoverflow.com/q/43471560/13860), the documentation for this package is inconsistent with its use of the 'skip_setup' option name.  Both `skip_setup` and `skipSetup` are used.  Are both of these names supported?  (If so, a documentation update is probably in order for the core PouchDB API).

I'm guessing the more likely case is that the documentation is just wrong here when it uses `skipSetup`, which is why I raised the issue here first.

**Comment by ptitjes** [comment]
Fixed by #153. Closing the issue.
