### ISSUE TITLE
6.2.0 update

### ISSUE THREAD

**Issue by semiautomatix** [pouchdb-community/pouchdb-authentication#148]
Hi,

Any plans for and update to keep up with the latest PouchDB changes?

Thanks

**Comment by froatsnook** [comment]
This would be a big help for me since the dependency on pouchdb-utils@6.0.3 is causing me to get multiple copies of pouchdb-utils, pouchdb-md5, pouchdb-promise, etc. in my bundle.

**Comment by ptitjes** [comment]
I opened issue #172 to use a version range for pouchdb dependencies.
Let's close this specific one.
