### ISSUE TITLE
Lodash dependency

### ISSUE THREAD

**Issue by natew** [pouchdb-community/pouchdb-authentication#149]
Was investigating big bundle size and found:

```
$ npm ls lodash

models@1.0.0 /Users/nw/projects/motion/starter/apps/models
└─┬ pouchdb-authentication@0.5.5
  └─┬ pouchdb-ajax@6.0.3
    └─┬ request@2.74.0
      └─┬ form-data@1.0.1
        └─┬ async@2.3.0
          └── lodash@4.17.4
```

Seems like a pretty deep dep of pouchdb-authentication is picking it up.

**Comment by ptitjes** [comment]
I guess we'd have less direct dependencies if we used a version range `^6`.
Do you have any other suggestion to reduce the depth of the dependency tree ?

**Comment by ptitjes** [comment]
Tracking the use of version ranges `^6` in #172. Closing this issue. Please open a new issue if you have any other suggestion on how to reduce our dependency tree.
