### ISSUE TITLE
Having the signup method attached to a db instance is missleading

### ISSUE THREAD

**Issue by danielo515** [pouchdb-community/pouchdb-authentication#151]
Hello,

If I understood correctly, the signup method just adds one user to the `_users` database. It does not adds the user to the current's database `_security` document. 
If that is the intended behavior, then why is that method part of the instance api ? Why it is not an static method? Having it attached to certain database can make an user like me that it adds an user to the `_users` database and then it adds it to the current referenced database, which is not the case.

If I misunderstood something, please feel free to correct me.
Regards

**Comment by ptitjes** [comment]
@danielo515 You have to use [pouchdb-security](https://github.com/pouchdb/pouchdb-server/tree/master/packages/node_modules/pouchdb-security) for that. However, IIRC, you'd have to have to be logged in with the correct admin role to do that. What you can do is assign a role (one that is already configured in the database's `_security`) to the user when you sign him up (as part of signUp options).

We could consider adding wrapper methods around `_security`. You are welcome to make any suggestion and/or PR.
