### ISSUE TITLE
One user per email ?

### ISSUE THREAD

**Issue by mikeCaine** [pouchdb-community/pouchdb-authentication#163]
Is it possible to check if email allready exists (without logic intervention) ? 
or 
one user per email ?

THX al lot +++ many many thx for your great works!!!!!!!!

Peace and greetings from Germany

**Comment by ptitjes** [comment]
That is possible if use a mango query on the `_users` database. Currently, there is a bug in CouchDB (https://github.com/apache/couchdb/issues/535), closed but not fixed. So you would have to replicate the database in a PouchDB instance. If you need further guidance, please ask.
