### ISSUE TITLE
Pouchdb authentication giving error: Could not find module `pouchdb-authentication` imported from `(require)`

### ISSUE THREAD

**Issue by flynsequeira** [pouchdb-community/pouchdb-authentication#164]
did npm install pouchdb-authentication 

Further at this step,
var PouchDB = require("pouchdb");
PouchDB.plugin(require('pouchdb-authentication'));

Could not find module `pouchdb-authentication` imported from `(require)`

**Comment by flynsequeira** [comment]
Static method worked. The other 2 didn't.

**Comment by Sushmitha-KK** [comment]
I am facing the exact same issue. But the static method also doesn't work in my case. It gives an error at the '.login()' function, saying that the function doesn't exist. 
in index.html
<script src="{{rootURL}}resources/js/pouchdb-authentication/dist/pouchdb.authentication.min.js"></script>

in app/authenticator/application.js
let remoteDb = new PouchDB("http://"+id+":"+password+"@localhost:5984/healthicate/", { skipSetup: true });
        this.db = remoteDb;
....
this.db.login(username, password).then((response) => {...

**Comment by ptitjes** [comment]
@flynsequeira, @Sushmitha-KK  Have you found what was you problem ?

**Comment by tomasvarg** [comment]
I've encountered the **db.login function doesn't exist** error after upgrading project's dependencies - it's just an assumption but as one of the upgrades was Webpack going from v2 to v3 and babel-loader v6 to v7, i think it might something to do with how one of them is treating default exports, anyways: by the force of console.log I've encountered that the result of `require('pouchdb-authentication')` is as expected on the server part run by babel-node but `{ default: ... }` on the client part run by webpack (the project is based on [js-stack-boilerplate](https://github.com/verekia/js-stack-boilerplate) where substantial amount of code is shared between server & client) ... so the solution for me was simply to use es6 module import syntax:
```
import PouchDB from 'pouchdb';
import PouchDBAuth from 'pouchdb-authentication';

PouchDB.plugin(PouchDBAuth)
```
or if you insist on require:
```
const PouchDBModule = require('pouchdb');
const PouchDBAuthModule = require('pouchdb-authentication');

const PouchDB = 'default' in PouchDBModule ? PouchDBModule.default : PouchDBModule;
const PouchDBAuth = 'default' in PouchDBAuthModule ? PouchDBAuthModule.default : PouchDBAuthModule;

PouchDB.plugin(PouchDBAuth)
```
There is some debate concerning the issues with default exports on the [webpack's github](https://github.com/webpack/webpack/issues/4742), at the time still opened though.

**Comment by ptitjes** [comment]
@tomasvarg Would you mind trying the following just to be sure ?

```
import * as PouchDB from 'pouchdb';
import * as PouchDBAuth from 'pouchdb-authentication';

PouchDB.plugin(PouchDBAuth)
```

**Comment by tomasvarg** [comment]
@ptitjes as done so the result is the same as using *require*: ok on babel-node & `{ default: ... }` on webpack-powered client.

Versions:
```
"pouchdb": "6.4.1"
"pouchdb-authentication": "1.1.0"
"webpack": "3.10.0",
"webpack-dev-server": "2.11.0"
"babel-loader": "7.1.2",
```

**Comment by ptitjes** [comment]
@tomasvarg It just appeared to me that you were giving a solution. So if it just works using ES6 imports, maybe I could close this bug. @flynsequeira ?

**Comment by ptitjes** [comment]
Closing this issue as it seems to be stale. Please do reopen a ticket if you still experience this.
