### ISSUE TITLE
Get CouchDB login dialog shown before db.login() runs

### ISSUE THREAD

**Issue by vardas-bill** [pouchdb-community/pouchdb-authentication#165]
I am using the pouchdb-authentication plugin in my ionic 3 App. When running the app in a web browser on my laptop I get an authentication dialog from the remote CouchDB database when the App executes db = new PouchDB(remote_url, options) and before db.login(name, pwd) runs. When the login does eventually run it returns success (if I enter the credentials in the dialog box fast enough).

This is my code:

```js
PouchDB.debug.enable('*');
PouchDB.plugin(PouchDBAuthentication);

// Hook up to the local calendar db (a replicate of the remote db)
this.localDB = new PouchDB('ehs-calendar', {auto_compaction: true});

// Hook up to the remote master news db
this.remoteDB = new PouchDB(COUCHDB_SERVER + '/ehs-calendar',
      {skip_setup: true } );

// Authenticate with the CouchDB db
this.remoteDB.login(COUCHDB_USER, COUCHDB_PASSWORD, function (err, response) {
      console.log("CalendarProvider: init(): remoteDB.login response is = " + JSON.stringify(response) + ', err = ' + JSON.stringify(err));
    });
```

**Comment by ptitjes** [comment]
I don't clearly understand what your problem is. Is that the browser pops up the authentication dialog and you'd like to suppress it ?

If that is the case then re-read the 'PouchDB Setup' section of the README.md. Indeed it clearly states to add a `skip_setup` option when you create the PouchDB instance:
> (Note that the users are shared across the entire CouchDB instance, not just mydb. Also, the skip_setup is to prevent PouchDB from doing any HTTP requests to the server while we're not logged in, which would cause a modal authentication popup.)

If this is not what you meant, then could you please try to rephrase your problem ?

**Comment by ptitjes** [comment]
@vardas-bill Sorry, I've just seen you indeed had the `skip_setup: true` set in your remote pouchdb options...

Could you precisely describe your environment (browser, ...) and give a test project so that I can try to reproduce it ?

**Comment by vardas-bill** [comment]
The problem has disappeared now. No idea why!
