### ISSUE TITLE
404 error while signing up ? 

### ISSUE THREAD

**Issue by lakinmohapatra** [pouchdb-community/pouchdb-authentication#167]
I am getting 404 error while signing up ?

**Comment by lakinmohapatra** [comment]
Please help

**Comment by lakinmohapatra** [comment]
The url is http://localhost:5984/_users/org.couchdb.user%3Alakalaka

**Comment by jpinkster** [comment]
@lakinmohapatra Do you mean creating a new user or signing in using the `.login()` method? What error are you getting?

**Comment by lukasborawski** [comment]
The same: https://github.com/pouchdb-community/pouchdb-authentication/issues/139#issuecomment-349942721

**Comment by ptitjes** [comment]
Closing this issue as it seems to be stale. Please do reopen a ticket if you still experience this.
