### ISSUE TITLE
TypeError: Promise is not a constructor

### ISSUE THREAD

**Issue by ptitjes** [pouchdb-community/pouchdb-authentication#170]
This error occurs when used in conjunction with PouchDB 6.3.4 as soon as you try to `login`.

**Comment by jpinkster** [comment]
+1

**Comment by ptitjes** [comment]
Fixed by #177.

**Comment by coderroggie** [comment]
Also receiving this error.  Any chance that there might be a release where this is fixed coming up?

**Comment by ptitjes** [comment]
@coderroggie Yes, it is coming up very soon. Please use a git npm dependency as a temporary measure.
