### ISSUE TITLE
session XHR error

### ISSUE THREAD

**Issue by mehrajpasha** [pouchdb-community/pouchdb-authentication#200]
I'm trying to authenticate using pouch db..I'm getting following error in pouchdb.min.js

pouchdb.authentication.min.js:1 
XHR failed loading: OPTIONS "http://_session/"

My custom authenticator file ;

`import Ember from 'ember';
import PouchDB from 'pouchdb';
import Base from 'ember-simple-auth/authenticators/base';
import config from "../config/environment";
export default Base.extend({
    init() {
        this._super(...arguments);
        let remoteDb = new PouchDB('http://localhost:5984', { skipSetup: true });
        this.db = remoteDb;
    },

    authenticate(username, password) {
        return new Ember.RSVP.Promise((resolve, reject) => {
            this.db.login(username, password).then((response) => {
                console.log("hajal");
                Ember.run(function() {
                    resolve({
                        name: response.name
                    });
                });
            }).catch((e) => {
                Ember.run(function() {
                    reject(e);
                    console.log(e);
                });
            })
        });
    },
 
});
`

**Comment by ptitjes** [comment]
@mehrajpasha Hi, I have no idea how `ember-simple-auth` works. I think you should open your issue [there](https://github.com/simplabs/ember-simple-auth) because they might not give PouchDB Authentication a correct URL. Do you have an online fiddle or something that we can debug ?

**Comment by mehrajpasha** [comment]
Hi, can u please tell me where do we write pouch db queries like db.find in ember projects ? controllers or routes or adapters ?

**Comment by ptitjes** [comment]
@mehrajpasha You have to ask that to the Ember project: https://github.com/emberjs/ember.js.
