### ISSUE TITLE
Login no longer works for non root databases

### ISSUE THREAD

**Issue by Brimstedt** [pouchdb-community/pouchdb-authentication#215]
## Expected Behavior

I expect to be able to login even if I have my database in a sub path on server:
https://xxx.yyy.com/db/dbname

In an older version, this was no problem

## Current Behavior

After upgrading to the latest version of the pouchdb-authentication plugin, Im unable to login if I have couchdb proxied on a sub path.

## Possible Solution

I think this is the breaking commit:
https://github.com/pouchdb-community/pouchdb-authentication/commit/74721352833886551b92db4e0f1b3093cc83fed7

If I test the previously used regex, it would extract the url as  `https://xxx.yyy.com/db` following my sample above. New method used (origin) returns only scheme + domain + port

Reverting those lines to using regex makes things work again.

## Steps to Reproduce (for bugs)

1. Put couchdb behind a proxy like nginx, proxying /db or similar to the db server
2. Try logging in

## Context

Unable to login users

## Your Environment

* Version of PouchDB Authentication: 1.1.1
* Version of PouchDB: 6.4.2
* Platform name and version:  Browsers 
* Operating System and version:  Linux, but most likely irrelevant 
* Server: CouchDB behing Nginx proxy

**Comment by ptitjes** [comment]
Hi @Brimstedt. Thank you very much for bug report.

Would you mind looking at the new test case and corresponding fix in #216 ?

Note that the `_session` URLs used for authentication are build with the same base URL as `_users` URLs (cf. https://github.com/pouchdb-community/pouchdb-authentication/blob/master/src/utils.js#L22-L28). So the new test case covers both.

Please test it and tell me if that fits your requirements.

**Comment by Brimstedt** [comment]
Hi, thanks for the quick fix.
I used your branch in my project and it seems to work well.

Unfortunately, I just get loads of errors when running the test suite, so I cannot verify tests. Code changes looks good though!
