### ISSUE TITLE
Cannot find type definition file for 'pouchdb-core' during transpile

### ISSUE THREAD

**Issue by silverbackdan** [pouchdb-community/pouchdb-authentication#222]
## Expected Behavior
Transpile should complete successfully

## Current Behavior
I get lots of errors all originating from the first error
```bash
Cannot find type definition file for 'pouchdb-core'. 
```

## Possible Solution
This was working fine yesterday and I'm not sure what has changed.

## Steps to Reproduce (for bugs)
1. Using cordova run `cordova run ios`

## Your Environment
* Version of PouchDB Authentication:  1.1.2
* Version of PouchDB: 6.4.3
* Platform name and version: npm v5.6.0 + node 9.2.0
* Operating System and version:  Mac OS High Sierra 10.13.3
* Server:  CouchDB
* Link to your project: (the project is private, sorry)

**Comment by silverbackdan** [comment]
Simple really
```bash
npm install --save @types/pouchdb-core
```

I just don't know why it was working before and not now. I don't think any packages updated (but I suppose I must be wrong).

**Comment by silverbackdan** [comment]
My other issue was unrelated, requiring the type definitions solved this issue.

**Comment by ptitjes** [comment]
@silverbackdan Great ! Cheers.
