### ISSUE TITLE
Authentication fail when using ":" in password (and probably username)

### ISSUE THREAD

**Issue by Dallas62** [pouchdb-community/pouchdb-authentication#228]
# Authentication fail when using ":" in password (and probably username)

## Expected Behavior
Using a password with ":" character should be allowed/encoded in URL.

## Current Behavior
CouchDB reject authentication (HTTP 401) because ":" is not encoded.

## Possible Solution
Follow [rfc3986](http://www.faqs.org/rfcs/rfc3986.html) and escape reserved characters with percent-encode value.
Found test case after reading  [escaping-username-characters-in-basic-auth-urls](https://stackoverflow.com/questions/6718471/escaping-username-characters-in-basic-auth-urls) and many users with the bug.

## Steps to Reproduce (for bugs)
1. Create an account in CouchDB that use ":" In password field.
2. Use pouchdb to login Couchdb.
3. Authentication fail.

## Context
This issue impact production users.
They are able to create account with all characters available on a phone, the backend create the account and secure it, then the client is connected to the Couchdb but with pouchdb-authentication.

I can put a workaround in the app to prevent "bad characters", but it should be handle in this library in my opinion.

## Your Environment
* Version of PouchDB Authentication: 1.1.2

**Comment by Dallas62** [comment]
I reproduce the bug only once, it's strange.
In all case from production, [nano](https://github.com/apache/couchdb-nano) login is working but pouchdb-authentication is not working with same values...

**Comment by ptitjes** [comment]
Hi @Dallas62, thank you very much for this detailed report.

I have not much time to look into your problem today but will look into it later this week.
However, from a quick glance at your description, it seems to me that you are using Basic Authentication with credentials provided in the URL. I did not know about using the escaping RFC for the credential parts.

In the meantime, you want to use the database options to provide the Basic Auth credentials, something like:
```
new PouchDB('url', {
  auth: {
    username: 'user',
    password: 'pass'
  }
}
```
See https://github.com/pouchdb-community/pouchdb-authentication/issues/204 and its fix https://github.com/pouchdb-community/pouchdb-authentication/commit/8b1d19130eed24dc10ce49165b563624d713ff43 for more information.

Sorry that it is not yet documented (contributions welcomed).

**Comment by Dallas62** [comment]
Thanks @ptitjes,

I'm using the method .login(username, password) to log users.
But I'm still investigating because I reproduce the bug only one time and it's really strange.
We are currently collecting informations with affected users to be sure it's the root-cause.

Informations we have actually:
- HTTP 401 from CouchDB ( /session endpoint ).
- Only from the client application (Mobile application in React-Native).
- Affects Android and iOS (many android/24).
- The bug seems to be stick on users, it doesn't disappear.
- Timestamp are too close for miss-click.
- And the only way to be disconnected from the Application just after backend login is:

```
        const username = AccountStore.credentials.email;
        const password = AccountStore.credentials.password;

        this.remoteDB.login(username, password, (err) => {
            if(err) {
                if('unauthorized' === err.error) {
                    AccountStore.signout();
                    return;
                }

```

I will update this issue and make a PR if needed.

**Comment by Dallas62** [comment]
Update:

No error from the library, it was a case sensitive error in username...

**Comment by ptitjes** [comment]
@Dallas62 Oh, great to hear ! Thanks for the feedback.
