### ISSUE TITLE
Can't detect user logOut or logIn in separate tab

### ISSUE THREAD

**Issue by DQvsRA** [pouchdb-community/pouchdb-authentication#230]
## Expected Behavior
Database event when logout (local and network)

## Current Behavior
Can't catch any events (for example in a separate tab)

## Possible Solution
Please add the event 

## Steps to Reproduce (for bugs)
1. Auth
2. Open another tab
3. You must be auth in a new tab too
4. logOut 
5. No events

**Comment by ptitjes** [comment]
Hi @DQvsRA. Thanks for your report.

I understand that you want all the tabs of your browser to be logged in/logged out with the same credentials and at the same time. Am I right ?

I just tried on one of my application and indeed I can be logged in (or not) with a different user in different tabs. I think this should be the expected default behaviour and that you would have to handle that on the application side. (But I'm curious btw how this can be implemented.)

I believe this is out of the scope of this library, so I will close this issue. Do not hesitate however to comment here if you find an easy way to implement cross-tab sharing of credentials.
