### ISSUE TITLE
Strange error on .logIn => status: 0, name: 'unknown'

### ISSUE THREAD

**Issue by greenais** [pouchdb-community/pouchdb-authentication#234]
## Expected Behavior
Existing user is logged in

## Current Behavior
.login (username, password) returns an error:
 { status: 0, name: 'unknown', message: undefined }

## Steps to Reproduce (for bugs)
My exact code:

```
'use strict';
import PouchDB from 'pouchdb-react-native';
PouchDB.plugin(require('pouchdb-authentication'));
const serverDB = new PouchDB('http://localhost:5984/test', {skip_setup: true})

const PDB = {};

PDB.login = ()=> {
  serverDB.logIn('user-123', '123')
  .then((res)=> {
    console.log(' =============> logIn res =============> ', res)
  })
  .catch((err)=> {
    console.log(' !!!!!!!!!!!!!!!!!! logIn ERR !!!!!!!! ', err)
  })
}
module.exports = PDB;
```
test DB exists on couchDB and has members permisson set for role 'registered';
User 'user-123' exists and has password '123' and role 'registered';
Calling PDB.login throws an error  `{ status: 0, name: 'unknown', message: undefined }`, so no DB operations are possible;

## Context
When I perform GET request to /test/_all_docs using basic authentication and same credentials - it works like a charm, got 200 status and rows in response. Wrong credentials return 401 status, as expected, which means that probably server config is Ok (at least with basic authentication).

## My Environment
* Version of PouchDB Authentication: 1.1.2
* Version of PouchDB: "pouchdb-react-native": "6.4.1",
* Platform name and version:  "react-native": "0.55.3"
* Operating System and version:  Windows 8.1, Android emulator
* Server:  CouchDB 2.1.1

**Comment by greenais** [comment]
The issue was related to wrong CouchDB hostname in remote DB setup: 
as long as RN app runs on android emulator, localhost, off cause, belongs to emulator, not to host machine where CouchDB is waiting for requests.
Changing to standard for android emulator host IP 10.0.2.2 fixes the issue.
My fault, sorry for disturbing.

**Comment by ptitjes** [comment]
@greenais No problem ! Glad you solved it !

As for the error message, we are using PouchDB ajax module and the error comes from it. I expect the message to be more clear when we will move to using `fetch` in the next PouchDB major release.
