### ISSUE TITLE
High vulnerability

### ISSUE THREAD

**Issue by broerse** [pouchdb-community/pouchdb-authentication#249]
`npm audit` Gives me one high vulnerability coming from pouchdb-authentication.

```
High            Open Redirect
Package         url-parse
Patched in      >=1.4.3
Dependency of   pouchdb-authentication
Path            pouchdb-authentication > url-parse
More info       https://nodesecurity.io/advisories/678
```

**Comment by ptitjes** [comment]
Later this week, I will update the dependencies to fix the many vulnerabilities.

**Comment by servocoder** [comment]
Looking forward

**Comment by dbugshe2** [comment]
Hi, @ptitjes  just checking, are we still on track for this fix. I'm really looking forward to this fix. cheers

**Comment by ptitjes** [comment]
I tried to fix it some days ago. However the npm server was outputing errors while auditing. I'd be grateful if one of you would like to make a PR.

**Comment by dbugshe2** [comment]
Thanks for clarifying. I'll give a try too and send a PR if it sticks.

**Comment by ptitjes** [comment]
@stanlemon Yep, I'll do a release this weekend.

**Comment by Didericis** [comment]
I'm still getting a security warning. Despite the update, my `package-lock.json` thinks `pouchdb-authentication` requires `url-parse` version `1.2.0`. This is what the `pouchdb-authentication` section of my `package-lock.json` looks like:

```json
    "pouchdb-authentication": {
      "version": "1.1.3",
      "resolved": "https://registry.npmjs.org/pouchdb-authentication/-/pouchdb-authentication-1.1.3.tgz",
      "integrity": "sha512-xzxmqAK6+rtJlVcFwebLBDlY0dDD5aqEb+bT0xStFp3s6HPC1QEa9C1NzkBScNBb8UG2BygTrVRMJzJLTR2LrA==",
      "requires": {
        "inherits": "2.0.3",
        "pouchdb-ajax": "~6.4.0",
        "pouchdb-binary-utils": "~6.4.0",
        "pouchdb-promise": "~6.4.0",
        "pouchdb-utils": "~6.4.0",
        "url-join": "4.0.0",
        "url-parse": "1.2.0"
      }
    },
```

**Comment by sudo-plz** [comment]
Hi @ptitjes, would it be possible to tag a version with the fix. I'm looking forward, thanks in advance!

**Comment by SinanGabel** [comment]
Some of the other libraries - and the code using these - probably also need an upgrade/change e.g.
pouchdb-ajax
pouchdb-promise 
pouchdb-utils

**Comment by uaru** [comment]
Maybe this is because the version number in package.json in master needs to be bumped to 1.1.4? Because now it lists dependency on url-parse 1.4.3, but the version of pouchdb is still 1.1.3, and that release still requires 1.2.0.

Of course there is workaround of installing from GitHub, but it should go to NPM...
