### ISSUE TITLE
Recommended setting of CouchDB configuration: {couch_httpd_auth: timeout} parameter

### ISSUE THREAD

**Issue by SinanGabel** [pouchdb-community/pouchdb-authentication#29]
Hi!
Is there a recommended setting of the CouchDB configuration: {couch_httpd_auth: timeout} parameter?

The reason for asking is that the default cookie refresh time is 10 minutes in pouchdb-authentication, and  without being 100% sure I seem to get problems if I set the timeout parameter to less than 10 minutes.

Best,
Sinan

**Comment by nolanlawson** [comment]
What kinds of problems do you get?

**Comment by SinanGabel** [comment]
I seem to get an error 500 when trying to access the db after timeout time where timeout is less than 10 minutes: but I will check this again as this seems to be a new observation.

**Comment by SinanGabel** [comment]
I tried, for the experiment, to set couch_httpd_auth: timeout=60 (corresponding to: 60 seconds=1 minute).

After about 5 minutes I could not read or write to the database. A pop-up came up and asked for re-login to the database. 

I am by the way using your fine guideline about using:
ajaxOpts = {ajax: {headers: {Authorization: 'Basic ' + utf8_to_b64(user.name + ':' + user.password) }}};

**Comment by SinanGabel** [comment]
PS I tried again today, and this time it took about 9 minutes before the request to read from the database failed, and the sign-on pop-up opened - by cancelling the sign-on a '401 (Unauthorized)' is replied in the browser console window.

Doing a db.allDocs() directly in the browser console window the error.status 500 is returned: '{status: 500, name: "unknown_error", message: "Database encountered an unknown error", error: true, toString: function}'

**Comment by nolanlawson** [comment]
It sounds like your CouchDB is not accessible from your browser. Did you set the `bind_address` to 0.0.0.0 and enable CORS?

**Comment by SinanGabel** [comment]
I am experimenting on a local single machine, and yes, CORS is set, and the bind_address is 127.0.0.1

Note that if the {couch_httpd_auth: timeout} parameter is set to a large number such as e.g. 1,209,600 (two weeks) then I do not experience any problems accessing data: then everything seems fine.

In other words, is there a lower limit of the value of the {couch_httpd_auth: timeout} parameter, given a default cookie refresh time of 10 minutes in pouchdb-authentication? (Here I presume that there is a relationship between these two parameter settings)

**Comment by nolanlawson** [comment]
Hm, I don't recall setting a timeout anywhere in pouchdb-authentication. That's really weird.

**Comment by SinanGabel** [comment]
Sorry: I mean the {couch_httpd_auth: timeout} parameter in the CouchDB configuration (i.e. not PouchDB or pouchdb-authentication library).

**Comment by nolanlawson** [comment]
Yeah sorry, I still don't know. :) This might be a CouchDB bug.

**Comment by SinanGabel** [comment]
No prob. I can pose the question at the CouchDB forum and see if anybody else have experienced this.

Thanks for now!
