### ISSUE TITLE
.signup() to create new db admin

### ISSUE THREAD

**Issue by fgrs** [pouchdb-community/pouchdb-authentication#36]
can I use this method to create an admin user type?

**Comment by nolanlawson** [comment]
no, you would need to POST to the `_config` endpoint and add their admin credentials there. I'd happily accept a pull request for `signupAdmin()`, though. :)

**Comment by James-Byrne** [comment]
Hi there, Im interested in working on this. Just to clarify though are you talking about creating Server Admins or users assigned an admin role?

**Comment by nolanlawson** [comment]
Users assigned an admin role.

**Comment by ptitjes** [comment]
There are now new `signUpAdmin(username, password)` and `deleteAdmin(username)` methods available in the pouchdb-authentication API since https://github.com/pouchdb-community/pouchdb-authentication/commit/cb8991dad0abd880b09f139c4d8c43099fa5d656.
