### ISSUE TITLE
[Docs] db.login example may return 403 (forbidden) instead of 401 (unauthorized)

### ISSUE THREAD

**Issue by renato** [pouchdb-community/pouchdb-authentication#80]
I'm using Cloudant, so I don't know if this is something specific to it, but the db.login example:

``` javascript
db.login('superman', 'clarkkent', function (err, response) {
  if (err) {
    if (err.name === 'unauthorized') {
      // name or password incorrect
    } else {
      // cosmic rays, a meteor, etc.
    }
```

didn't work when the user/password were wrong.

This is the err object returned:

``` javascript
CustomPouchError {
  status: 403,
  name: "forbidden",
  message: "Forbidden by design doc validate_doc_update function",
  error: true,
  reason: "Name or password is incorrect"
}
```

**Comment by nolanlawson** [comment]
I'm happy to update the docs to mention this. I believe on CouchDB it is indeed a 401.

**Comment by renato** [comment]
Yes, CouchDB returns a 401 (https://wiki.apache.org/couchdb/Session_API).

Just wanted to mention this because I believe some people (like myself) may use Cloudant as a "quick start" to CouchDB. In my code I checked err.status for 401 and 403 just to be on the safe side.

**Comment by sebrojas14** [comment]
Please help, I always got that error with Cloudant, I created the user like this:

{
 "_id": "3ae2b004f63f76a1d936b0cce2e96d2c",
 "_rev": "3-77f93ee6a9e99d6769dc528c0bcb82bf",
 "value": {
  "rev": "3-77f93ee6a9e99d6769dc528c0bcb82bf"
 },
 "key": "3ae2b004f63f76a1d936b0cce2e96d2c",
 "doc": {
  "_id": "3ae2b004f63f76a1d936b0cce2e96d2c",
  "_rev": "3-77f93ee6a9e99d6769dc528c0bcb82bf",
  "name": "admin",
  "roles": [
   "_reader",
   "_writer"
  ],
  "type": "user",
  "password": "37d6c5Qe"
 }
}

And I always got the error, using this library o with out it. I tested creating a user with signIn but other error appears. There is something I have to change to the user document?
