### ISSUE TITLE
OAuth Support

### ISSUE THREAD

**Issue by adamhalasz** [pouchdb-community/pouchdb-authentication#81]
It would be nice to have support for OAuth signup, login and requests
http://docs.couchdb.org/en/stable/api/server/authn.html#oauth-authentication

Thanks,
Adam

**Comment by ptitjes** [comment]
@adamhalasz Is it still supported by CouchDB ? There is nothing about OAuth in the page you linked ? Are you using an external CouchDB addon ?

**Comment by stanlemon** [comment]
Oauth 1.0 was removed in 2.1, see https://github.com/apache/couchdb/issues/656

**Comment by ptitjes** [comment]
OK. Thanks @stanlemon. Closing this issue then.
