### ISSUE TITLE
Scenario: Everyone has to be logged in to do anything

### ISSUE THREAD

**Issue by andreujuanc** [pouchdb-community/pouchdb-authentication#86]
Hello,

I'm having a small issue here, and im not sure if its because its late or there is something to be improved on couchdb/pouchdb side.

I set a role on access so only user with that rose are able to do something right?
But then i saw the _session handler is also blocked?So how can only a logged in user be allowed to do log in?

I cant save admin credentials on client side.

How can I accomplish this? 
Is it possible?
For now, i dont want any blackmagic security, just that logged in users are validated and can get data.

Any ideas?

Thanks!

**Comment by nolanlawson** [comment]
I'm sorry, but I'm not really sure what you mean? Are you talking about [this setup from the README](https://github.com/nolanlawson/pouchdb-authentication#everybody-has-to-be-logged-in-to-do-anything)? What do you mean when you say that the _session handler is also blocked?
